// ============================================
// AGROBASE V3 — Emission Factor Database
// IPCC 2019 Refinement Guidelines + Country-Specific
// Uganda (UG), Ghana (GH), Kenya (KE)
// ============================================

import type { EmissionFactor, EmissionSource, CarbonStandard } from './types'

/**
 * Comprehensive emission factor database for East/West African agriculture.
 * Sources: IPCC 2019 Refinement Guidelines, national GHG inventories,
 * FAO statistics, peer-reviewed literature for tropical smallholder systems.
 */
export const EMISSION_FACTORS: EmissionFactor[] = [
  // ─────────────────────────────────────────────
  // FERTILIZER — NPK, Urea, DAP, Organic Manure
  // ─────────────────────────────────────────────
  {
    source: 'FERTILIZER',
    commodity: 'NPK',
    country: 'UG',
    value: 4.23,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement Vol 4 Ch 11; Uganda NDC 2021',
    year: 2021,
    uncertainty: 30,
  },
  {
    source: 'FERTILIZER',
    commodity: 'NPK',
    country: 'GH',
    value: 4.15,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement Vol 4 Ch 11; Ghana EPA National Inventory',
    year: 2021,
    uncertainty: 28,
  },
  {
    source: 'FERTILIZER',
    commodity: 'NPK',
    country: 'KE',
    value: 4.31,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement Vol 4 Ch 11; Kenya NDC 2020',
    year: 2020,
    uncertainty: 25,
  },
  {
    source: 'FERTILIZER',
    commodity: 'UREA',
    country: 'UG',
    value: 3.86,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement; EF1 = 0.012 for UG (tropical humid)',
    year: 2021,
    uncertainty: 30,
  },
  {
    source: 'FERTILIZER',
    commodity: 'UREA',
    country: 'GH',
    value: 3.78,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement; EF1 = 0.011 for GH (tropical moist)',
    year: 2021,
    uncertainty: 28,
  },
  {
    source: 'FERTILIZER',
    commodity: 'UREA',
    country: 'KE',
    value: 3.92,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement; EF1 = 0.013 for KE (tropical highland)',
    year: 2020,
    uncertainty: 25,
  },
  {
    source: 'FERTILIZER',
    commodity: 'DAP',
    country: 'UG',
    value: 4.05,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement; DAP = 18-46-0 N content',
    year: 2021,
    uncertainty: 30,
  },
  {
    source: 'FERTILIZER',
    commodity: 'DAP',
    country: 'GH',
    value: 3.98,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement; Ghana DAP application data',
    year: 2021,
    uncertainty: 28,
  },
  {
    source: 'FERTILIZER',
    commodity: 'DAP',
    country: 'KE',
    value: 4.12,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement; Kenya DAP application data',
    year: 2020,
    uncertainty: 25,
  },
  {
    source: 'FERTILIZER',
    commodity: 'ORGANIC_MANURE',
    country: 'UG',
    value: 0.68,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement; Tropical manure EF, ~2% N content',
    year: 2021,
    uncertainty: 50,
  },
  {
    source: 'FERTILIZER',
    commodity: 'ORGANIC_MANURE',
    country: 'GH',
    value: 0.62,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement; Ghana manure composition data',
    year: 2021,
    uncertainty: 50,
  },
  {
    source: 'FERTILIZER',
    commodity: 'ORGANIC_MANURE',
    country: 'KE',
    value: 0.71,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement; Kenya manure composition data',
    year: 2020,
    uncertainty: 50,
  },

  // ─────────────────────────────────────────────
  // PESTICIDE — Herbicides, Insecticides, Fungicides
  // ─────────────────────────────────────────────
  {
    source: 'PESTICIDE',
    commodity: 'GLYPHOSATE',
    country: 'UG',
    value: 14.6,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'Ecoinvent 3.8; Glyphosate manufacturing LCA',
    year: 2022,
    uncertainty: 20,
  },
  {
    source: 'PESTICIDE',
    commodity: 'GLYPHOSATE',
    country: 'GH',
    value: 14.6,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'Ecoinvent 3.8; Glyphosate manufacturing LCA',
    year: 2022,
    uncertainty: 20,
  },
  {
    source: 'PESTICIDE',
    commodity: 'GLYPHOSATE',
    country: 'KE',
    value: 14.6,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'Ecoinvent 3.8; Glyphosate manufacturing LCA',
    year: 2022,
    uncertainty: 20,
  },
  {
    source: 'PESTICIDE',
    commodity: 'MANCOZEB',
    country: 'UG',
    value: 18.3,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'Ecoinvent 3.8; Mancozeb manufacturing LCA',
    year: 2022,
    uncertainty: 25,
  },
  {
    source: 'PESTICIDE',
    commodity: 'MANCOZEB',
    country: 'GH',
    value: 18.3,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'Ecoinvent 3.8; Mancozeb manufacturing LCA',
    year: 2022,
    uncertainty: 25,
  },
  {
    source: 'PESTICIDE',
    commodity: 'MANCOZEB',
    country: 'KE',
    value: 18.3,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'Ecoinvent 3.8; Mancozeb manufacturing LCA',
    year: 2022,
    uncertainty: 25,
  },
  {
    source: 'PESTICIDE',
    commodity: 'CYPERMETHRIN',
    country: 'UG',
    value: 22.1,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'Ecoinvent 3.8; Pyrethroid manufacturing LCA',
    year: 2022,
    uncertainty: 25,
  },
  {
    source: 'PESTICIDE',
    commodity: 'CYPERMETHRIN',
    country: 'GH',
    value: 22.1,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'Ecoinvent 3.8; Pyrethroid manufacturing LCA',
    year: 2022,
    uncertainty: 25,
  },
  {
    source: 'PESTICIDE',
    commodity: 'CYPERMETHRIN',
    country: 'KE',
    value: 22.1,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'Ecoinvent 3.8; Pyrethroid manufacturing LCA',
    year: 2022,
    uncertainty: 25,
  },
  {
    source: 'PESTICIDE',
    commodity: 'COPPER_FUNGICIDE',
    country: 'UG',
    value: 6.8,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'Ecoinvent 3.8; Copper-based fungicide LCA',
    year: 2022,
    uncertainty: 20,
  },
  {
    source: 'PESTICIDE',
    commodity: 'COPPER_FUNGICIDE',
    country: 'GH',
    value: 6.8,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'Ecoinvent 3.8; Copper-based fungicide LCA',
    year: 2022,
    uncertainty: 20,
  },
  {
    source: 'PESTICIDE',
    commodity: 'COPPER_FUNGICIDE',
    country: 'KE',
    value: 6.8,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'Ecoinvent 3.8; Copper-based fungicide LCA',
    year: 2022,
    uncertainty: 20,
  },

  // ─────────────────────────────────────────────
  // FUEL — Diesel, Petrol
  // ─────────────────────────────────────────────
  {
    source: 'FUEL',
    commodity: 'DIESEL',
    country: 'UG',
    value: 2.68,
    unit: 'litre',
    tier: 'IPCC_TIER1',
    sourceReference: 'IPCC 2019 Refinement Vol 2 Ch 3; default diesel EF',
    year: 2019,
    uncertainty: 5,
  },
  {
    source: 'FUEL',
    commodity: 'DIESEL',
    country: 'GH',
    value: 2.68,
    unit: 'litre',
    tier: 'IPCC_TIER1',
    sourceReference: 'IPCC 2019 Refinement Vol 2 Ch 3; default diesel EF',
    year: 2019,
    uncertainty: 5,
  },
  {
    source: 'FUEL',
    commodity: 'DIESEL',
    country: 'KE',
    value: 2.68,
    unit: 'litre',
    tier: 'IPCC_TIER1',
    sourceReference: 'IPCC 2019 Refinement Vol 2 Ch 3; default diesel EF',
    year: 2019,
    uncertainty: 5,
  },
  {
    source: 'FUEL',
    commodity: 'PETROL',
    country: 'UG',
    value: 2.31,
    unit: 'litre',
    tier: 'IPCC_TIER1',
    sourceReference: 'IPCC 2019 Refinement Vol 2 Ch 3; default petrol EF',
    year: 2019,
    uncertainty: 5,
  },
  {
    source: 'FUEL',
    commodity: 'PETROL',
    country: 'GH',
    value: 2.31,
    unit: 'litre',
    tier: 'IPCC_TIER1',
    sourceReference: 'IPCC 2019 Refinement Vol 2 Ch 3; default petrol EF',
    year: 2019,
    uncertainty: 5,
  },
  {
    source: 'FUEL',
    commodity: 'PETROL',
    country: 'KE',
    value: 2.31,
    unit: 'litre',
    tier: 'IPCC_TIER1',
    sourceReference: 'IPCC 2019 Refinement Vol 2 Ch 3; default petrol EF',
    year: 2019,
    uncertainty: 5,
  },

  // ─────────────────────────────────────────────
  // LAND USE CHANGE — Forest→Crop, Grassland→Crop
  // ─────────────────────────────────────────────
  {
    source: 'LAND_USE_CHANGE',
    commodity: 'FOREST_TO_CROP',
    country: 'UG',
    value: 127.5,
    unit: 'hectare',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement Vol 4 Ch 2; Uganda forest C stock 127.5 tC/ha',
    year: 2021,
    uncertainty: 40,
  },
  {
    source: 'LAND_USE_CHANGE',
    commodity: 'FOREST_TO_CROP',
    country: 'GH',
    value: 142.3,
    unit: 'hectare',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement Vol 4 Ch 2; Ghana forest C stock 142.3 tC/ha',
    year: 2021,
    uncertainty: 40,
  },
  {
    source: 'LAND_USE_CHANGE',
    commodity: 'FOREST_TO_CROP',
    country: 'KE',
    value: 118.6,
    unit: 'hectare',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement Vol 4 Ch 2; Kenya forest C stock 118.6 tC/ha',
    year: 2020,
    uncertainty: 40,
  },
  {
    source: 'LAND_USE_CHANGE',
    commodity: 'GRASSLAND_TO_CROP',
    country: 'UG',
    value: 29.4,
    unit: 'hectare',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement Vol 4 Ch 2; Tropical grassland soil C',
    year: 2021,
    uncertainty: 50,
  },
  {
    source: 'LAND_USE_CHANGE',
    commodity: 'GRASSLAND_TO_CROP',
    country: 'GH',
    value: 26.8,
    unit: 'hectare',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement Vol 4 Ch 2; Ghana savanna soil C',
    year: 2021,
    uncertainty: 50,
  },
  {
    source: 'LAND_USE_CHANGE',
    commodity: 'GRASSLAND_TO_CROP',
    country: 'KE',
    value: 32.1,
    unit: 'hectare',
    tier: 'IPCC_TIER2',
    sourceReference: 'IPCC 2019 Refinement Vol 4 Ch 2; Kenya rangeland soil C',
    year: 2020,
    uncertainty: 50,
  },

  // ─────────────────────────────────────────────
  // TRANSPORT — Truck, Motorcycle (country-specific)
  // ─────────────────────────────────────────────
  {
    source: 'TRANSPORT',
    commodity: 'TRUCK',
    country: 'UG',
    value: 0.162,
    unit: 'km',
    tier: 'IPCC_TIER2',
    sourceReference: 'Uganda MoEF transport inventory; 20-tonne truck, 40% load factor',
    year: 2021,
    uncertainty: 15,
  },
  {
    source: 'TRANSPORT',
    commodity: 'TRUCK',
    country: 'GH',
    value: 0.155,
    unit: 'km',
    tier: 'IPCC_TIER2',
    sourceReference: 'Ghana EPA transport inventory; 20-tonne truck, 45% load factor',
    year: 2021,
    uncertainty: 15,
  },
  {
    source: 'TRANSPORT',
    commodity: 'TRUCK',
    country: 'KE',
    value: 0.148,
    unit: 'km',
    tier: 'IPCC_TIER2',
    sourceReference: 'Kenya NCCAP transport data; 20-tonne truck, 50% load factor',
    year: 2020,
    uncertainty: 15,
  },
  {
    source: 'TRANSPORT',
    commodity: 'MOTORCYCLE',
    country: 'UG',
    value: 0.048,
    unit: 'km',
    tier: 'IPCC_TIER2',
    sourceReference: 'Uganda MoEF; 125cc motorcycle average',
    year: 2021,
    uncertainty: 20,
  },
  {
    source: 'TRANSPORT',
    commodity: 'MOTORCYCLE',
    country: 'GH',
    value: 0.051,
    unit: 'km',
    tier: 'IPCC_TIER2',
    sourceReference: 'Ghana EPA; 125cc motorcycle, older fleet avg',
    year: 2021,
    uncertainty: 20,
  },
  {
    source: 'TRANSPORT',
    commodity: 'MOTORCYCLE',
    country: 'KE',
    value: 0.044,
    unit: 'km',
    tier: 'IPCC_TIER2',
    sourceReference: 'Kenya NCCAP; 125cc motorcycle, newer fleet',
    year: 2020,
    uncertainty: 20,
  },
  {
    source: 'TRANSPORT',
    commodity: 'PICKUP',
    country: 'UG',
    value: 0.215,
    unit: 'km',
    tier: 'IPCC_TIER2',
    sourceReference: 'Uganda MoEF; 4x4 pickup, 30% load factor',
    year: 2021,
    uncertainty: 18,
  },
  {
    source: 'TRANSPORT',
    commodity: 'PICKUP',
    country: 'GH',
    value: 0.210,
    unit: 'km',
    tier: 'IPCC_TIER2',
    sourceReference: 'Ghana EPA; 4x4 pickup average',
    year: 2021,
    uncertainty: 18,
  },
  {
    source: 'TRANSPORT',
    commodity: 'PICKUP',
    country: 'KE',
    value: 0.198,
    unit: 'km',
    tier: 'IPCC_TIER2',
    sourceReference: 'Kenya NCCAP; 4x4 pickup, better road network',
    year: 2020,
    uncertainty: 18,
  },

  // ─────────────────────────────────────────────
  // PROCESSING — Coffee, Cocoa, Maize, Rice
  // ─────────────────────────────────────────────
  {
    source: 'PROCESSING',
    commodity: 'COFFEE_PULPING',
    country: 'UG',
    value: 0.12,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'UCDA processing energy audit; wet pulping',
    year: 2022,
    uncertainty: 15,
  },
  {
    source: 'PROCESSING',
    commodity: 'COFFEE_MILLING',
    country: 'UG',
    value: 0.08,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'UCDA processing audit; diesel hulling + grading',
    year: 2022,
    uncertainty: 15,
  },
  {
    source: 'PROCESSING',
    commodity: 'COFFEE_PULPING',
    country: 'KE',
    value: 0.11,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Kenya Coffee Board; mill energy audit',
    year: 2021,
    uncertainty: 15,
  },
  {
    source: 'PROCESSING',
    commodity: 'COFFEE_MILLING',
    country: 'KE',
    value: 0.07,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Kenya Coffee Board; milling audit',
    year: 2021,
    uncertainty: 15,
  },
  {
    source: 'PROCESSING',
    commodity: 'COCOA_FERMENTATION',
    country: 'GH',
    value: 0.03,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Ghana COCOBOD fermentation study; manual process',
    year: 2022,
    uncertainty: 20,
  },
  {
    source: 'PROCESSING',
    commodity: 'COCOA_DRYING_PROCESS',
    country: 'GH',
    value: 0.18,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Ghana COCOBOD; sun drying + fire drying mix',
    year: 2022,
    uncertainty: 25,
  },
  {
    source: 'PROCESSING',
    commodity: 'MAIZE_MILLING',
    country: 'UG',
    value: 0.06,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'FAO Agro-processing energy data; hammer mill',
    year: 2021,
    uncertainty: 20,
  },
  {
    source: 'PROCESSING',
    commodity: 'MAIZE_MILLING',
    country: 'GH',
    value: 0.06,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'FAO Agro-processing energy data; hammer mill',
    year: 2021,
    uncertainty: 20,
  },
  {
    source: 'PROCESSING',
    commodity: 'MAIZE_MILLING',
    country: 'KE',
    value: 0.05,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'FAO Agro-processing energy data; hammer mill',
    year: 2020,
    uncertainty: 20,
  },
  {
    source: 'PROCESSING',
    commodity: 'RICE_MILLING',
    country: 'UG',
    value: 0.09,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'FAO Rice processing LCA; diesel-powered mill',
    year: 2021,
    uncertainty: 20,
  },
  {
    source: 'PROCESSING',
    commodity: 'RICE_MILLING',
    country: 'GH',
    value: 0.09,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'FAO Rice processing LCA; diesel-powered mill',
    year: 2021,
    uncertainty: 20,
  },
  {
    source: 'PROCESSING',
    commodity: 'RICE_MILLING',
    country: 'KE',
    value: 0.08,
    unit: 'kg',
    tier: 'IPCC_TIER1',
    sourceReference: 'FAO Rice processing LCA; Mwea irrigation scheme data',
    year: 2020,
    uncertainty: 20,
  },
  {
    source: 'PROCESSING',
    commodity: 'TEA_PROCESSING',
    country: 'KE',
    value: 0.25,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Kenya Tea Board; CTC processing energy audit',
    year: 2021,
    uncertainty: 15,
  },

  // ─────────────────────────────────────────────
  // IRRIGATION — Pump operation (diesel/electric)
  // ─────────────────────────────────────────────
  {
    source: 'IRRIGATION',
    commodity: 'DIESEL_PUMP',
    country: 'UG',
    value: 3.85,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Uganda MWE irrigation surveys; 5hp diesel pump per hour',
    year: 2021,
    uncertainty: 20,
  },
  {
    source: 'IRRIGATION',
    commodity: 'DIESEL_PUMP',
    country: 'GH',
    value: 3.72,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Ghana Irrigation Dev Authority; pump surveys',
    year: 2021,
    uncertainty: 20,
  },
  {
    source: 'IRRIGATION',
    commodity: 'DIESEL_PUMP',
    country: 'KE',
    value: 3.90,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Kenya NIA; Mwea irrigation scheme pump data',
    year: 2020,
    uncertainty: 20,
  },
  {
    source: 'IRRIGATION',
    commodity: 'ELECTRIC_PUMP',
    country: 'UG',
    value: 0.52,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Uganda UEGCL grid emission factor 0.52 kgCO2/kWh',
    year: 2022,
    uncertainty: 10,
  },
  {
    source: 'IRRIGATION',
    commodity: 'ELECTRIC_PUMP',
    country: 'GH',
    value: 0.43,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Ghana Energy Commission grid EF 0.43 kgCO2/kWh',
    year: 2022,
    uncertainty: 10,
  },
  {
    source: 'IRRIGATION',
    commodity: 'ELECTRIC_PUMP',
    country: 'KE',
    value: 0.32,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Kenya EPRA grid EF 0.32 kgCO2/kWh (geothermal mix)',
    year: 2022,
    uncertainty: 10,
  },

  // ─────────────────────────────────────────────
  // DRYING — Solar vs Mechanical
  // ─────────────────────────────────────────────
  {
    source: 'DRIEDING',
    commodity: 'SOLAR_DRYER',
    country: 'UG',
    value: 0.02,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'FAO Solar drying study Uganda; minimal fuel for fans',
    year: 2022,
    uncertainty: 30,
  },
  {
    source: 'DRIEDING',
    commodity: 'SOLAR_DRYER',
    country: 'GH',
    value: 0.02,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'FAO Solar drying study Ghana; minimal fuel for fans',
    year: 2022,
    uncertainty: 30,
  },
  {
    source: 'DRIEDING',
    commodity: 'SOLAR_DRYER',
    country: 'KE',
    value: 0.02,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'FAO Solar drying study Kenya; minimal fuel for fans',
    year: 2022,
    uncertainty: 30,
  },
  {
    source: 'DRIEDING',
    commodity: 'MECHANICAL_DRYER',
    country: 'UG',
    value: 0.35,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Uganda coffee drying; diesel-fired rotary dryer',
    year: 2022,
    uncertainty: 20,
  },
  {
    source: 'DRIEDING',
    commodity: 'MECHANICAL_DRYER',
    country: 'GH',
    value: 0.33,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Ghana maize/cocoa mechanical drying audit',
    year: 2022,
    uncertainty: 20,
  },
  {
    source: 'DRIEDING',
    commodity: 'MECHANICAL_DRYER',
    country: 'KE',
    value: 0.30,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Kenya grain dryer; natural gas/diesel mix',
    year: 2022,
    uncertainty: 20,
  },

  // ─────────────────────────────────────────────
  // STORAGE — Cold storage per kg per day
  // ─────────────────────────────────────────────
  {
    source: 'STORAGE',
    commodity: 'COLD_STORAGE',
    country: 'UG',
    value: 0.018,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Uganda cold chain study; diesel + electric backup',
    year: 2022,
    uncertainty: 25,
  },
  {
    source: 'STORAGE',
    commodity: 'COLD_STORAGE',
    country: 'GH',
    value: 0.016,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Ghana cold chain; grid-powered facility',
    year: 2022,
    uncertainty: 25,
  },
  {
    source: 'STORAGE',
    commodity: 'COLD_STORAGE',
    country: 'KE',
    value: 0.012,
    unit: 'kg',
    tier: 'IPCC_TIER2',
    sourceReference: 'Kenya cold chain; geothermal-powered grid',
    year: 2022,
    uncertainty: 25,
  },
]

/**
 * Country-specific N2O emission factors for direct soil emissions (IPCC Tier 2).
 * EF1 default = 0.01 kg N2O-N per kg N applied.
 * Adjusted for tropical climate zones per IPCC 2019 Refinement Table 11.1.
 */
const COUNTRY_N2O_EF: Record<string, number> = {
  UG: 0.012,  // Tropical humid — slightly higher
  GH: 0.011,  // Tropical moist — moderate
  KE: 0.013,  // Tropical highland — higher due to cooler temps, slower diffusion
}

/**
 * Look up an emission factor from the database.
 * Falls back to a wildcard country match if exact country not found.
 */
export function getEmissionFactor(
  source: EmissionSource,
  commodity: string,
  country: string,
): EmissionFactor | undefined {
  // Exact match first
  const exact = EMISSION_FACTORS.find(
    (ef) => ef.source === source && ef.commodity === commodity && ef.country === country,
  )
  if (exact) return exact

  // Fallback: try any country for same source+commodity (for commodity-specific factors)
  const anyCountry = EMISSION_FACTORS.find(
    (ef) => ef.source === source && ef.commodity === commodity,
  )
  return anyCountry
}

/**
 * Calculate N2O emissions from synthetic/organic N fertilizer application
 * using IPCC Tier 2 methodology (2019 Refinement, Vol 4, Chapter 11).
 *
 * Formula:
 *   N2O-N (kg) = N_applied (kg) × EF1
 *   N2O (kg) = N2O-N × (44/28)        [molecular weight ratio]
 *   CO2e (kg) = N2O × 298              [GWP of N2O = 298, AR5]
 *
 * @param nKgApplied  — total nitrogen applied in kg
 * @param country     — ISO code: UG, GH, KE
 * @returns           — total N2O emissions in kgCO2e
 */
export function calculateN2OEmissions(nKgApplied: number, country: string): number {
  const ef = COUNTRY_N2O_EF[country] ?? 0.01
  const n2oN = nKgApplied * ef
  const n2o = n2oN * (44 / 28)
  const co2e = n2o * 298
  return Math.round(co2e * 100) / 100
}